#!/usr/bin/env node
// Generates src/app/tokens.css from design/styles.json (the Framer export).
// Run manually after design/styles.json changes: node scripts/build-tokens.mjs

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const data = JSON.parse(readFileSync(join(root, "design/styles.json"), "utf8"));

const slugify = (name) =>
  name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");

const colorSlug = new Map(data.colorStyles.map((c) => [c.name, slugify(c.name)]));

const fontVar = (family) => {
  if (family === "Big Shoulders") return "var(--font-big-shoulders)";
  if (family === "Chivo Mono") return "var(--font-chivo-mono)";
  return "var(--font-chivo)";
};

let css = `/* Generated by scripts/build-tokens.mjs from design/styles.json. Do not edit by hand. */\n\n`;

css += `@theme {\n`;
for (const c of data.colorStyles) {
  css += `  --color-${colorSlug.get(c.name)}: ${c.light};\n`;
}
css += `}\n\n`;

for (const t of data.textStyles) {
  const slug = slugify(t.name);
  const colorRef = colorSlug.get(t.colorStyleRef?.name) ?? "frost";
  const transform = t.textTransform && t.textTransform !== "none" ? t.textTransform : null;

  css += `.text-${slug} {\n`;
  css += `  font-family: ${fontVar(t.font.family)};\n`;
  css += `  font-weight: ${t.font.weight};\n`;
  css += `  font-size: ${t.fontSize};\n`;
  css += `  line-height: ${t.lineHeight};\n`;
  css += `  letter-spacing: ${t.letterSpacing};\n`;
  css += `  color: var(--color-${colorRef});\n`;
  if (transform) css += `  text-transform: ${transform};\n`;
  if (t.paragraphSpacing) css += `  margin-bottom: ${t.paragraphSpacing}px;\n`;
  css += `}\n`;

  // Breakpoints are Framer's own registered widths (Desktop 1200 / Tablet 810);
  // sizes shrink below each, so emit them as max-width overrides.
  const sorted = [...(t.breakpoints ?? [])].sort((a, b) => b.minWidth - a.minWidth);
  for (const bp of sorted) {
    css += `@media (max-width: ${bp.minWidth - 1}px) {\n`;
    css += `  .text-${slug} {\n`;
    css += `    font-size: ${bp.fontSize};\n`;
    css += `    line-height: ${bp.lineHeight};\n`;
    css += `    letter-spacing: ${bp.letterSpacing};\n`;
    if (bp.paragraphSpacing !== undefined) css += `    margin-bottom: ${bp.paragraphSpacing}px;\n`;
    css += `  }\n`;
    css += `}\n`;
  }
  css += `\n`;
}

writeFileSync(join(root, "src/app/tokens.css"), css);
console.log(
  `Generated src/app/tokens.css: ${data.colorStyles.length} colors, ${data.textStyles.length} text styles.`
);
